### PR TITLE
feat!: rewrite module

### PR DESCRIPTION
**Pull request by Geminii**
Rewrite module as Typescript and purpose some changes : 

- [x] Rewrite in Typescript
- [x] Add default options for `manifest` & `workbox`
- [x] Rewrite test using `nuxt/test-utils`
- [x] Rewrite utils in Typescript
- [x] Respect convention about `src` directory

Thanks @pi0 to offer me the possibility to discover this module and rewrite it 😀❤️

One question : 
- How can i test this condition ? https://github.com/Geminii/onesignal-module/blob/ba93d2464afae1a0465823b693cb80e6d9a903e2/src/utils.ts#L18

### CODE REVIEW

**Comment by productfrontenddeveloper** [comment]
is this place forgotten :) when pushed ?

**Comment by lopermo** [comment]
Can we accept this PR?

**Comment by impowski** [comment]
When this one is going to land?

**Comment by lopermo** [comment]
@pi0 Could you please review this PR?

**Pull request merged**
